=== thelesenok/SQL-Search/backend/src/main/resources/model/schema.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="definition" type="modelDefinition"/>

  <xs:complexType name="modelDefinition">
    <xs:sequence>
      <xs:element name="type" type="typeDefinition" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="typeDefinition">
    <xs:all>
      <xs:element name="type" type="xs:string"/>
      <xs:element name="table" type="xs:string"/>
      <xs:element name="properties" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="property" type="propertyDefinition" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:all>
  </xs:complexType>

  <xs:complexType name="propertyDefinition">
    <xs:all>
      <xs:element name="property" type="xs:string"/>
      <xs:element name="column" type="xs:string"/>
      <xs:element name="type" type="propertyType" minOccurs="0"/>
      <xs:element name="display-property" type="xs:boolean"/>
      <xs:element name="reference" type="typeReference" minOccurs="0"/>
    </xs:all>
  </xs:complexType>

  <xs:complexType name="typeReference">
    <xs:sequence>
      <xs:element name="type" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="propertyType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="REFERENCE"/>
      <xs:enumeration value="STRING"/>
      <xs:enumeration value="NUMBER"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== thelesenok/SQL-Search/backend/src/test/resources/model/test_types.xml
<?xml version="1.0" encoding="UTF-8"?>
<definition xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema.xsd">
    <type>
        <type>project</type>
        <table>PROJECTS</table>
        <properties>
            <property>
                <type>STRING</type>
                <property>string-property</property>
                <column>STRING_COLUMN</column>
                <display-property>false</display-property>
                <primary-key>false</primary-key>
            </property>
            <property>
                <type>NUMBER</type>
                <property>number-property</property>
                <column>NUMBER_COLUMN</column>
                <display-property>false</display-property>
                <primary-key>false</primary-key>
            </property>
            <property>
                <type>REFERENCE</type>
                <property>reference-property</property>
                <column>FOREIGN_COLUMN</column>
                <display-property>false</display-property>
                <primary-key>false</primary-key>
                <reference>
                    <type>EXECUTORS</type>
                </reference>
            </property>
        </properties>
    </type>
    <type>
        <type>executor</type>
        <table>EXECUTORS</table>
        <properties>
            <property>
                <property>PK</property>
                <column>EXECUTORS_ID</column>
                <display-property>false</display-property>
                <primary-key>true</primary-key>
            </property>
            <property>
                <primary-key>false</primary-key>
                <property>executor_name</property>
                <column>EXECUTOR_FULL_NAME</column>
                <display-property>true</display-property>
            </property>
        </properties>
    </type>
    <type>
        <type>stage</type>
        <table>STAGES</table>
    </type>
</definition>

=== thelesenok/SQL-Search/backend/src/main/resources/model/model.xml
<?xml version="1.0" encoding="UTF-8"?>
<definition xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema.xsd">
    <type>
        <type>project</type>
        <table>PROJECTS</table>
        <properties>
            <property>
                <property>string-property-name</property>
                <type>STRING</type>
                <column>STRING_COLUMN</column>
                <display-property>false</display-property>
                <reference>
                    <type>user</type>
                </reference>
            </property>
        </properties>
    </type>
</definition>

=== thelesenok/SQL-Search/backend/src/main/resources/model/test_types.xml
<?xml version="1.0" encoding="UTF-8"?>
<definition xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema.xsd">
    <type>
        <type>project</type>
        <table>PROJECTS</table>
        <properties>
            <property>
                <type>STRING</type>
                <property>string-property</property>
                <column>STRING_COLUMN</column>
                <display-property>false</display-property>
            </property>
            <property>
                <type>NUMBER</type>
                <property>number-property</property>
                <column>NUMBER_COLUMN</column>
                <display-property>false</display-property>
            </property>
            <property>
                <type>REFERENCE</type>
                <property>reference-property</property>
                <column>FOREIGN_COLUMN</column>
                <display-property>false</display-property>
                <reference>
                    <type>executor</type>
                </reference>
            </property>
        </properties>
    </type>
    <type>
        <type>executor</type>
        <table>EXECUTORS</table>
    </type>
    <type>
        <type>stage</type>
        <table>STAGES</table>
    </type>
</definition>
